### ISSUE TITLE
Any Plan for the GTA 4 1.2.0.43 Update? (Steam Version)

### ISSUE THREAD

**Issue by Ekooo08** [ahmed605/SparkIV#4]
Rockstar seems to have updated the game. the current SparkIV isn't working on the current version.

**Comment by ahmed605** [comment]
Can you provide the exe for that version?

**Comment by amrshaheen61** [comment]
@ahmed605 

Do you need exe file only

**Comment by ahmed605** [comment]
> @ahmed605 
> 
> Do you need exe file only

Yes

**Comment by amrshaheen61** [comment]
@ahmed605 
These are the basic files, but some of the files are not game-specific, and I no longer remember the files

http://www.mediafire.com/file/nie7t3totefrtz7/Gta.zip/file

**Comment by ahmed605** [comment]
> @ahmed605 
> These are the basic files, but some of the files are not game-specific, and I no longer remember the files
> 
> http://www.mediafire.com/file/nie7t3totefrtz7/Gta.zip/file

Is the exe in the archive modified? (If yes then I can't use it because offsets change)

**Comment by amrshaheen61** [comment]
No 
@ahmed605

**Comment by ahmed605** [comment]
@amrshaheen61 the PE/exe file you sent has the same key offset as v1.2.0.32 PE/exe (which is supported) so that can mean one of these:
- the current app version works with v1.2.0.43
- the PE/exe you sent isn't for v1.2.0.43

try the current version here: https://github.com/ahmed605/SparkIV/releases/download/v0.8.56/Beta.zip

**Comment by Ekooo08** [comment]
I Just Tried it with the v1.2.0.43. It Works Like a Charm :)

**Comment by ahmed605** [comment]
@Ekooo08 Thanks for confirming that :+1:
